// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDemander = "demander"

// Demander mapped from table <demander>
type Demander struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Category    string    `gorm:"column:category;not null" json:"category"`
	Brand       string    `gorm:"column:brand;not null" json:"brand"`
	Io          string    `gorm:"column:io;not null" json:"io"`
	FiscalYear  string    `gorm:"column:fiscal_year;not null" json:"fiscal_year"`
	BudgetOwner string    `gorm:"column:budget_owner;not null" json:"budget_owner"`
	BrandFa     string    `gorm:"column:brand_fa;not null" json:"brand_fa"`
	CreateTime  time.Time `gorm:"column:create_time" json:"create_time"`
	CreateBy    string    `gorm:"column:create_by" json:"create_by"`
	ModifyTime  time.Time `gorm:"column:modify_time" json:"modify_time"`
	ModifyBy    string    `gorm:"column:modify_by" json:"modify_by"`
	Deleted     []uint8   `gorm:"column:deleted" json:"deleted"`
}

// TableName Demander's table name
func (*Demander) TableName() string {
	return TableNameDemander
}
