// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDictionary = "dictionary"

// Dictionary mapped from table <dictionary>
type Dictionary struct {
	ID    int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Label string `gorm:"column:label;not null" json:"label"`
	Value string `gorm:"column:value;not null" json:"value"`
	Type  string `gorm:"column:type;not null" json:"type"`
	PIds  string `gorm:"column:pIds" json:"pIds"`
}

// TableName Dictionary's table name
func (*Dictionary) TableName() string {
	return TableNameDictionary
}
