// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMessageConfiguration = "message_configuration"

// MessageConfiguration mapped from table <message_configuration>
type MessageConfiguration struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ConfigKey    string    `gorm:"column:config_key;not null" json:"config_key"`
	ConfigValue  string    `gorm:"column:config_value;not null" json:"config_value"`
	CreateTime   time.Time `gorm:"column:create_time" json:"create_time"`
	CreateBy     string    `gorm:"column:create_by" json:"create_by"`
	ModifyTime   time.Time `gorm:"column:modify_time" json:"modify_time"`
	ModifyBy     string    `gorm:"column:modify_by" json:"modify_by"`
	TemplateCode string    `gorm:"column:template_code;not null" json:"template_code"`
	Deleted      []uint8   `gorm:"column:deleted;not null" json:"deleted"`
}

// TableName MessageConfiguration's table name
func (*MessageConfiguration) TableName() string {
	return TableNameMessageConfiguration
}
