// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMessageTemplate = "message_template"

// MessageTemplate mapped from table <message_template>
type MessageTemplate struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TemplateName string    `gorm:"column:template_name;not null" json:"template_name"`
	TemplateCode string    `gorm:"column:template_code;not null" json:"template_code"`
	Type         string    `gorm:"column:type;not null" json:"type"`
	Content      string    `gorm:"column:content;not null" json:"content"`
	CreateTime   time.Time `gorm:"column:create_time" json:"create_time"`
	CreateBy     string    `gorm:"column:create_by" json:"create_by"`
	ModifyTime   time.Time `gorm:"column:modify_time" json:"modify_time"`
	ModifyBy     string    `gorm:"column:modify_by" json:"modify_by"`
	Deleted      []uint8   `gorm:"column:deleted;not null" json:"deleted"`
	BrandID      int64     `gorm:"column:brand_id" json:"brand_id"`
	TokenID      string    `gorm:"column:token_id" json:"token_id"`
	Sign         string    `gorm:"column:sign" json:"sign"`
	PrimaryISP   string    `gorm:"column:primary_ISP" json:"primary_ISP"`
	UserID       string    `gorm:"column:user_id" json:"user_id"`
	ExtCode      string    `gorm:"column:ext_code" json:"ext_code"`
	Brand        string    `gorm:"column:brand" json:"brand"`
	Provider     string    `gorm:"column:provider" json:"provider"`
	Region       string    `gorm:"column:region;comment:国家地区" json:"region"` // 国家地区
	Providers    string    `gorm:"column:providers" json:"providers"`
	DemanderIds  string    `gorm:"column:demander_ids" json:"demander_ids"`
}

// TableName MessageTemplate's table name
func (*MessageTemplate) TableName() string {
	return TableNameMessageTemplate
}
