// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMsgProvider = "msg_provider"

// MsgProvider mapped from table <msg_provider>
type MsgProvider struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ProviderCode string    `gorm:"column:provider_code;not null" json:"provider_code"`
	ProviderName string    `gorm:"column:provider_name;not null" json:"provider_name"`
	Description  string    `gorm:"column:description" json:"description"`
	CreateTime   time.Time `gorm:"column:create_time" json:"create_time"`
	CreateBy     string    `gorm:"column:create_by" json:"create_by"`
	ModifyTime   time.Time `gorm:"column:modify_time" json:"modify_time"`
	ModifyBy     string    `gorm:"column:modify_by" json:"modify_by"`
	Deleted      []uint8   `gorm:"column:deleted;not null" json:"deleted"`
}

// TableName MsgProvider's table name
func (*MsgProvider) TableName() string {
	return TableNameMsgProvider
}
