// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameReport = "report"

// Report mapped from table <report>
type Report struct {
	ID                     int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	FiscalYear             string    `gorm:"column:fiscal_year" json:"fiscal_year"`
	Month                  string    `gorm:"column:month" json:"month"`
	Brand                  string    `gorm:"column:brand" json:"brand"`
	Io                     string    `gorm:"column:io" json:"io"`
	EstimatedXChargeAmount float64   `gorm:"column:estimated_x_charge_amount" json:"estimated_x_charge_amount"`
	MsgDeliveryNum         int32     `gorm:"column:msg_delivery_num" json:"msg_delivery_num"`
	BudgetOwner            string    `gorm:"column:budget_owner" json:"budget_owner"`
	BrandFa                string    `gorm:"column:brand_fa" json:"brand_fa"`
	RealXChargeAmount      float64   `gorm:"column:real_x_charge_amount" json:"real_x_charge_amount"`
	XChargeStatus          bool      `gorm:"column:x_charge_status" json:"x_charge_status"`
	Remark                 string    `gorm:"column:remark" json:"remark"`
	CreateTime             time.Time `gorm:"column:create_time" json:"create_time"`
	CreateBy               string    `gorm:"column:create_by" json:"create_by"`
	ModifyTime             time.Time `gorm:"column:modify_time" json:"modify_time"`
	ModifyBy               string    `gorm:"column:modify_by" json:"modify_by"`
	Deleted                []uint8   `gorm:"column:deleted" json:"deleted"`
	SmsDeliveryNum         int32     `gorm:"column:sms_delivery_num" json:"sms_delivery_num"`
	MmsDeliveryNum         int32     `gorm:"column:mms_delivery_num" json:"mms_delivery_num"`
	GlobalSmsDeliveryNum   int32     `gorm:"column:global_sms_delivery_num" json:"global_sms_delivery_num"`
	GcOperationCosts       float64   `gorm:"column:gc_operation_costs" json:"gc_operation_costs"`
	CampaignServiceCosts   float64   `gorm:"column:campaign_service_costs" json:"campaign_service_costs"`
}

// TableName Report's table name
func (*Report) TableName() string {
	return TableNameReport
}
