// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameReportDetail = "report_detail"

// ReportDetail mapped from table <report_detail>
type ReportDetail struct {
	ID                int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Date              string    `gorm:"column:date" json:"date"`
	Category          string    `gorm:"column:category" json:"category"`
	Brand             string    `gorm:"column:brand" json:"brand"`
	BudgetOwner       string    `gorm:"column:budget_owner" json:"budget_owner"`
	Io                string    `gorm:"column:io" json:"io"`
	MessageType       string    `gorm:"column:message_type" json:"message_type"`
	StartTime         string    `gorm:"column:start_time" json:"start_time"`
	Vendor            string    `gorm:"column:vendor" json:"vendor"`
	CampaignName      string    `gorm:"column:campaign_name" json:"campaign_name"`
	CampaignID        string    `gorm:"column:campaign_id" json:"campaign_id"`
	ExtCode           string    `gorm:"column:ext_code" json:"ext_code"`
	Region            string    `gorm:"column:region" json:"region"`
	Sign              string    `gorm:"column:sign" json:"sign"`
	MsgDeliveryNum    int32     `gorm:"column:msg_delivery_num" json:"msg_delivery_num"`
	MsgSucceedNum     int32     `gorm:"column:msg_succeed_num" json:"msg_succeed_num"`
	MsgSucceedPercent string    `gorm:"column:msg_succeed_percent" json:"msg_succeed_percent"`
	PeopleSucceedNum  int32     `gorm:"column:people_succeed_num" json:"people_succeed_num"`
	CreateTime        time.Time `gorm:"column:create_time" json:"create_time"`
	CreateBy          string    `gorm:"column:create_by" json:"create_by"`
	ModifyTime        time.Time `gorm:"column:modify_time" json:"modify_time"`
	ModifyBy          string    `gorm:"column:modify_by" json:"modify_by"`
	Deleted           []uint8   `gorm:"column:deleted" json:"deleted"`
	Month             string    `gorm:"column:month" json:"month"`
	FiscalYear        string    `gorm:"column:fiscal_year" json:"fiscal_year"`
	BrandFa           string    `gorm:"column:brand_fa" json:"brand_fa"`
}

// TableName ReportDetail's table name
func (*ReportDetail) TableName() string {
	return TableNameReportDetail
}
