// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameScene = "scene"

// Scene mapped from table <scene>
type Scene struct {
	ID                 int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ExtCode            int32     `gorm:"column:ext_code;not null" json:"ext_code"`
	Account            string    `gorm:"column:account" json:"account"`
	MarketingProgramID int32     `gorm:"column:marketing_program_id;not null" json:"marketing_program_id"`
	App                string    `gorm:"column:app;not null" json:"app"`
	Sign               string    `gorm:"column:sign" json:"sign"`
	TokenID            string    `gorm:"column:token_id" json:"token_id"`
	Prolonged          []uint8   `gorm:"column:prolonged;not null" json:"prolonged"`
	CreateTime         time.Time `gorm:"column:create_time" json:"create_time"`
	ModifyTime         time.Time `gorm:"column:modify_time" json:"modify_time"`
	CreateBy           string    `gorm:"column:create_by" json:"create_by"`
	ModifyBy           string    `gorm:"column:modify_by" json:"modify_by"`
	Deleted            []uint8   `gorm:"column:deleted" json:"deleted"`
	SceneResultTopic   string    `gorm:"column:scene_result_topic" json:"scene_result_topic"`
}

// TableName Scene's table name
func (*Scene) TableName() string {
	return TableNameScene
}
